// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/templates/FirstLightCyclingLookbook-wVEPjE/ClikClakDuskMix.tsx": () => import("../components/mockups/templates/FirstLightCyclingLookbook-wVEPjE/ClikClakDuskMix.tsx")
};
